name: news_app
description: A simple news app using Flutter and state management.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  url_launcher: ^6.1.7
  share_plus: ^7.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

